// Datos de las catorce fichas de lectura: qué se ve en cada letra y qué concepto de Relevo evoca.
// c = concepto (2 = lo evoca con claridad, 1 = en parte). n = notas atadas a una letra (l) o a toda la palabra (todo).
module.exports = [
  {
    id: 'struggle', k: 'nw:struggle', nombre: 'Struggle', rol: 'logotipo',
    autoria: 'Autoría sin nombre propio en la página', origen: 'Klotter Supply', lic: 'ofl', enlace: 'https://klotter.supply/struggle',
    fuente: 'La página la presenta como una tipografía abierta para la comunicación de base, parte de un trabajo de título sobre diseño y sostenibilidad.',
    c: { Testigo: 2, Calma: 2 },
    n: [
      { l: 'l', t: 'La «l» es una columna alta, más ancha en los extremos que en el centro. Parece un testigo agarrado por la cintura.' },
      { l: 'o', t: 'La «o» y la «e» son cápsulas con una ranura como contraforma: la misma forma que ya usa la interfaz.' },
      { l: 'r', t: 'La «r» es un tallo grueso con un brazo corto y remate de gota; el cuello se pellizca al unirse.' },
    ],
    cuidado: 'Las contraformas son ranuras: a 16 px quedan como una línea fina. Es muy pesada y tiene un solo peso. Nació para el activismo: conviene mirar si ese tono encaja con una voz sin reproche.',
  },
  {
    id: 'bespoke-stencil', k: 'fk:bespoke-stencil', nombre: 'Bespoke Stencil', rol: 'logotipo',
    autoria: 'Jérémie Hornus, Théo Guillard, Morgane Pambrun, Alisa Nowak y Joachim Vu', origen: 'Fontshare', lic: 'fs', enlace: 'https://www.fontshare.com/fonts/bespoke-stencil',
    fuente: 'Fontshare la describe como una sans humanista que parece de plantilla: cada trazo se interrumpe donde quien escribe con pluma ancha haría una pausa. La lámina la muestra en Bold; hay cinco pesos.',
    c: { Pausa: 2, Calma: 2, Lugar: 1, Traspaso: 1 },
    n: [
      { l: 'e', t: 'La «e» y la «v» tienen un corte pequeño en la unión de los trazos, justo donde la pluma se detendría.' },
      { l: 'o', t: 'Las contraformas de la «o» y la «e» son amplias y abiertas, y se leen a cualquier tamaño.' },
      { l: 'todo', t: 'Tiene cinco pesos con cursivas y no tiene remates: es la más versátil para titulares y para la app.' },
    ],
    cuidado: 'Los cortes son sutiles. De lejos se lee como una sans humanista cualquiera; el carácter está en el detalle. Hay que ver si alcanza para ser un logotipo.',
  },
  {
    id: 'manosque', k: 'nw:manosque', nombre: 'Manosque', rol: 'logotipo',
    autoria: 'Ariel Martín Pérez (París)', origen: 'Tunera', lic: 'ofl', enlace: 'https://www.tunera.xyz/fonts/manosque/',
    fuente: 'Tunera cuenta que parte del rótulo de la estación de tren de Manosque y de la rotulación pública francesa de fines del siglo XIX y comienzos del XX, dibujada con pincel plano.',
    c: { Lugar: 2, Calma: 2, Testigo: 1 },
    n: [
      { l: 'o', t: 'La «o» y la «e» son rectángulos altos de esquinas redondas, con una contraforma vertical y estrecha: una ventanilla.' },
      { l: 'l', t: 'La «l» lleva una pequeña bandera arriba y un pie corto abajo, como un poste con su cartel.' },
      { l: 'r', t: 'La «r» tiene un brazo grueso y curvo con remate redondo; el pincel plano deja los bordes algo irregulares.' },
    ],
    cuidado: 'Es condensada y muy negra, con aire de cartel rústico, y tiene un solo peso. Hay que probar si junto al azul se siente casera o campestre.',
  },
  {
    id: 'kola', k: 'fk:kola', nombre: 'Kola', rol: 'logotipo',
    autoria: 'Jean-Baptiste Morizot (París)', origen: 'Fontshare', lic: 'fs', enlace: 'https://www.fontshare.com/fonts/kola',
    fuente: 'Fontshare la describe como una sans de plantilla tecnoide, con todos los remates redondos y un aire de pantalla LED.',
    c: { Traspaso: 2, Señal: 2, Testigo: 1, Pausa: 1 },
    n: [
      { l: 'v', t: 'La «v» son dos trazos que no se tocan. Queda un hueco entre ellos, el sitio donde una parte entrega y la otra recibe.' },
      { l: 'l', t: 'La «l» se parte en una pieza alta y otra con base: cada letra se interrumpe en un punto, como si pasara de una pieza a otra.' },
      { l: 'o', t: 'Todos los trazos terminan en punta redonda: son cápsulas, con un corte a cada lado de la «o».' },
    ],
    cuidado: 'El aire de pantalla LED puede sentirse más frío que casero. La «r» con pie ancho es poco común y se lee como «r» solo en contexto. Tiene un solo peso.',
  },
  {
    id: 'ouroboros', k: 'vw:ouroboros', nombre: 'Ouroboros', rol: 'logotipo',
    autoria: 'Ariel Martín Pérez con H·Alix Sanyas (2018, actualizada en 2021)', origen: 'Velvetyne', lic: 'ofl', enlace: 'https://velvetyne.fr/fonts/ouroboros/',
    fuente: 'Velvetyne la clasifica como serif, fantasía y hecha a mano.',
    c: { Volver: 2, Calma: 1 },
    n: [
      { l: 'o', t: 'La «o» entra en espiral hacia el centro: la palabra termina volviendo sobre sí misma. Es la lectura más literal de «vuelve».' },
      { l: 'e', t: 'La «e» tiene la contraforma inclinada y una cola que sube, como un ojo.' },
      { l: 'v', t: 'La «v» tiene una contraforma en gota entre dos trazos gruesos con remates.' },
    ],
    cuidado: 'Es un display gordo de aire setentero. Como serif, choca con la regla «sin serif» de la propuesta 3.4 si se usa fuera del logotipo; en tamaños pequeños la espiral se cierra.',
  },
  {
    id: 'striper', k: 'fk:striper', nombre: 'Striper', rol: 'señal',
    autoria: 'Jitka Janečková', origen: 'Fontshare', lic: 'fs', enlace: 'https://www.fontshare.com/fonts/striper',
    fuente: 'Fontshare explica que cada trazo recto se reemplaza por un patrón de cebra, que conviene usarla en tamaños grandes y con pocas palabras, y que trae dos alternativas por letra.',
    c: { Señal: 2, Pausa: 2 },
    n: [
      { l: 'o', t: 'La «o» es un anillo de rayos: se lee como una señal que irradia, o como un reloj.' },
      { l: 'l', t: 'La «l» queda en peldaños, como una escalera: pasos.' },
      { l: 'e', t: 'La «e» tiene barras verticales, como un ecualizador.' },
    ],
    cuidado: 'El tono es festivo, de circo, y a 16 px las rayas se funden. Sirve para una sola palabra grande; la barra de la app queda fuera.',
  },
  {
    id: 'ampoule', k: 'nw:ampoule', nombre: 'Ampoule', rol: 'señal',
    autoria: 'Ando', origen: 'Tunera', lic: 'ofl', enlace: 'https://www.tunera.xyz/fonts/ampoule/',
    fuente: 'Tunera explica que se dibuja con tres piezas (un punto y dos cápsulas, de doble y triple altura) sobre una matriz estricta, que se inspira en los tableros de información del transporte público y que se lee mejor en tamaños pequeños que grandes. Nació como homenaje al videojuego Cyberpunk 2077.',
    c: { Señal: 2, Lugar: 2, Testigo: 1 },
    n: [
      { l: 'todo', t: 'Punto y cápsula: un alfabeto de puntos y rayas, como el código Morse. Se lee como una luz de aviso.' },
      { l: 'l', t: 'La «l» es una cápsula larga con dos puntos en cada extremo y dos en el centro: un testigo con sus extremos marcados.' },
      { l: 'v', t: 'La «v» son dos cápsulas y tres puntos, y se parece a una «u».' },
    ],
    cuidado: 'En mayúsculas, «RELEVO» puede leerse «RELUO». A 24 px los puntos se funden en una trama; Tunera dice que se lee mejor chica, y en esta prueba a 1× no se vio. Su origen es una distopía de ciencia ficción, que choca con el tono casero de Relevo.',
  },
  {
    id: 'hyper-scrypt', k: 'vw:hyper-scrypt', nombre: 'Hyper Scrypt', rol: 'cartel',
    autoria: 'Jérémy Landes (2018)', origen: 'Velvetyne', lic: 'ofl', enlace: 'https://velvetyne.fr/fonts/hyper-scrypt/',
    fuente: 'Velvetyne cuenta que se diseñó para la exposición Hyper Chapelle; la clasifica como letra de plantilla.',
    c: { Lugar: 2, Traspaso: 2, Señal: 1 },
    n: [
      { l: 'todo', t: 'Cada letra tiene un corte horizontal a media altura: dos mitades con un hueco entre ellas.' },
      { l: 'o', t: 'La «o» es un anillo dentro de otro, como una diana.' },
      { l: 'todo', t: 'La plantilla es la técnica con que se marca un lugar con pintura.' },
    ],
    cuidado: 'Solo mayúsculas (la minúscula dibuja lo mismo) y muy pesada. A 16 px los cortes la vuelven un código de barras.',
  },
  {
    id: 'pilowlava', k: 'vw:pilowlava', nombre: 'Pilowlava', rol: 'cartel',
    autoria: 'Anton Moglia y Jérémy Landes, con Maksym Kobuzan (2019, actualizada en 2024)', origen: 'Velvetyne', lic: 'ofl', enlace: 'https://velvetyne.fr/fonts/pilowlava/',
    fuente: 'Velvetyne ofrece dos estilos, Regular y Atome; la lámina muestra Atome, que añade los agujeros. Según Velvetyne, Typographica la incluyó entre sus tipografías favoritas de 2019.',
    c: { Calma: 2, Traspaso: 1, Lugar: 1 },
    n: [
      { l: 'todo', t: 'Cada letra es una tira doblada. En la variante Atome lleva agujeros, como remaches, en los extremos y en los dobleces: los puntos de unión quedan marcados.' },
      { l: 'o', t: 'La «o» es un cuadrado redondeado con un triángulo vacío en el centro y agujeros en las esquinas.' },
      { l: 'e', t: 'La «E» doblada en zigzag se parece a una «Z»; en la palabra completa se reconoce.' },
    ],
    cuidado: 'Solo mayúsculas y muy juguetona. Es de las más anchas: «relevo» mide 149 px a 32 px de cuerpo (Manosque, 79 px).',
  },
  {
    id: 'westgate', k: 'nw:westgate', nombre: 'Westgate', rol: 'cartel',
    autoria: 'Republish, de Behalf Studio', origen: 'Republish', lic: 'ofl', enlace: 'https://republi.sh/',
    fuente: 'La página cuenta que parte de la tipografía de concreto de las puertas del mercado Bến Thành de Saigón, instaladas en una renovación de mediados del siglo XX, con una forma condensada de inspiración Art Déco.',
    c: { Lugar: 2, Testigo: 1 },
    n: [
      { l: 'todo', t: 'La proporción es altísima y estrecha, como el vano de una puerta: el sitio por donde se pasa.' },
      { l: 'o', t: 'La «o» es una cápsula vertical.' },
      { l: 'v', t: 'La «v» es muy angosta y cierra en un vértice casi plano.' },
    ],
    cuidado: 'Solo mayúsculas y muy condensada. Tiene poco cuerpo para el ícono de la app.',
  },
  {
    id: 'patriot', k: 'nw:patriot', nombre: 'Patriot', rol: 'cartel',
    autoria: 'Republish, de Behalf Studio', origen: 'Republish', lic: 'ofl', enlace: 'https://republi.sh/',
    fuente: 'La página cuenta que se inspira en la portada rotulada a mano de un cancionero histórico del Museo Hồ Chí Minh y destaca sus barras irregulares.',
    c: { Traspaso: 1, Lugar: 1 },
    n: [
      { l: 'r', t: 'Las barras de la «R» y de la «E» atraviesan el tallo y sobresalen a la izquierda: la barra pasa de un lado al otro.' },
      { l: 'o', t: 'La «O» es un círculo casi perfecto.' },
      { l: 'v', t: 'La «V» termina en una U apuntada.' },
    ],
    cuidado: 'Solo mayúsculas, de peso muy alto, y la «V» se parece a una «U». El nombre («Kháng chiến», resistencia) y su origen remiten a un cancionero de guerra: conviene conocer ese contexto antes de usarla en una marca doméstica.',
  },
  {
    id: 'blackout', k: 'nw:blackout', nombre: 'Blackout', rol: 'cartel',
    autoria: 'Tyler Finck', origen: 'The League of Moveable Type', lic: 'ofl', enlace: 'https://www.theleagueofmoveabletype.com/blackout',
    fuente: 'La página la muestra con la frase «Eats holes for breakfast, lunch and dinner».',
    c: { Lugar: 2, Traspaso: 1 },
    n: [
      { l: 'todo', t: 'Las letras son huecos recortados en un bloque negro: el vacío tiene la forma de la letra.' },
      { l: 'r', t: 'Cada letra queda en su casilla, como una ficha de etiqueta.' },
      { l: 'o', t: 'La «O» es un estadio vertical, otra cápsula.' },
    ],
    cuidado: 'Solo mayúsculas y sin acentos (faltan á, é, í, ó, ú, ñ, ¿ y ¡). El bloque negro es muy pesado.',
  },
  {
    id: 'roubaix', k: 'nw:roubaix', nombre: 'Roubaix Industrielle', rol: 'cartel',
    autoria: 'Ariel Martín Pérez (París)', origen: 'Tunera', lic: 'ofl', enlace: 'https://www.tunera.xyz/fonts/roubaix-industrielle/',
    fuente: 'Tunera cuenta que se hizo por encargo de la oficina de turismo de Roubaix y del taller Bien Vu, con módulos en forma de ladrillo y, en los tamaños ópticos pequeños, conexiones que recuerdan las costuras de los textiles. Es toda en mayúsculas.',
    c: { Traspaso: 1, Pausa: 1, Señal: 1 },
    n: [
      { l: 'todo', t: 'Cada trazo es una cadena de módulos que se enganchan: las piezas encajan unas con otras, como puntadas que unen dos telas.' },
      { l: 'e', t: 'Los trazos parecen una onda cuadrada, la forma con que se dibuja una señal digital. La fuente habla de costuras; esta lectura es mía.' },
      { l: 'v', t: 'La «V» termina en dos rayitas planas y se parece a una «U».' },
    ],
    cuidado: 'Solo mayúsculas; la «V» se lee «U». El dibujo cambia con el tamaño óptico, así que habría que elegir uno.',
  },
  {
    id: 'linea', k: 'l75:linea', nombre: 'Linea', rol: 'señal',
    autoria: 'Typothèque de l’ESA le 75 (talleres de estudiantes, Bruselas)', origen: 'Le75', lic: 'gpl', enlace: 'https://typotheque.le75.be/',
    fuente: 'El sitio pide acreditar a los dibujantes y a la typothèque.',
    c: { Señal: 2, Calma: 1 },
    n: [
      { l: 'todo', t: 'Cada trazo son cinco líneas paralelas, que vibran como un eco.' },
      { l: 'o', t: 'La «o» son óvalos concéntricos desplazados, como ondas.' },
      { l: 'r', t: 'La «r» abre su brazo en abanico: irradia.' },
    ],
    cuidado: 'Son cinco hilos finos: a 16 px se funden en un trazo gris y la letra se lee, pero se pierde el eco. Faltan í, ó, ú, ñ, ¿ y ¡. La licencia GNU/GPL se declara en el sitio, pero el zip no trae el texto.',
  },
];
